- name: install needed packages
  hosts: all
  become: true
  tasks:
    - name: install tools
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10
      apt:
        pkg:
          - qemu
          - qemu-user-static
          - qemu-utils
          - binfmt-support
          - qemu-user-static
          - dosfstools
          - systemd-container
          - wget
          - binutils
          - debootstrap
          - git
          - util-linux
          - fdisk
          - e2fsprogs
          - parted
          - golang
    - name: install hashicorp apt key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: install hashicorp apt repo
      apt_repository:
        repo: deb https://apt.releases.hashicorp.com buster hashicorp
        codename: buster
        update_cache: yes
    - name: install packer
      register: packer_status
      until: packer_status is success
      delay: 6
      retries: 10
      apt:
        name: packer
    - name: create plugin directory
      file:
        path: /home/serena/packer-arm
        state: directory
        mode: '0755'
    - name: clone packer plugin repo
      git:
        repo: https://github.com/mkaczanowski/packer-builder-arm
        dest: /home/serena/packer-arm
        version: d4cf21a2313c41d9d7d02a1a58986fa00cec7f1a
        refspec: HEAD
    - name: move scripts
      copy:
        src: '/tmp/compress.bash'
        dest: '/home/serena/compress.bash'
    - name: move scripts
      copy:
        src: '/tmp/install.bash'
        dest: '/home/serena/install.bash'
    - name: move scripts
      copy:
        src: '/tmp/setup.bash'
        dest: '/home/serena/setup.bash'
