- name: install needed packages
  hosts: all
  become: true
  tasks:
    - name: install tools
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10
      apt:
        pkg:
          - qemu
          - qemu-user-static
          - qemu-utils
          - binfmt-support
          - qemu-user-static
          - dosfstools
          - systemd-container
          - wget
          - binutils
          - debootstrap
          - git
          - util-linux
          - fdisk
          - e2fsprogs
          - parted
          - golang
